ORIGINAL_IMAGE_PATH = "data/orange_frog.jpg"
IMAGE_2_PATH = "data/orange_frog_2.jpg"
OUTPUT_IMAGE_PATH = "data/modified_image.jpg"

# BASIC OPENCV OPERATIONS
RESIZE_IMAGE = False
CONVERT_TO_GRAYSCALE = True
ADD_TEXT_TO_IMAGE = False
MODIFY_PIXEL_VALUE = False
FLIP_IMAGE = False
ROTATE_IMAGE_MULTIPLE_90 = False
CROP_IMAGE = False

# ADVANCED OPENCV OPERATIONS
EDGE_DETECTION = False
CHANGE_COLOR_SPACE = False
ORB_FEATURE_DETECTOR = False
MATCH_KEY_POINTS = False
