ORIGINAL_IMAGE_PATH = "data/orange_frog.jpg"
OUTPUT_IMAGE_PATH = "data/modified_image.jpg"

# BASIC OPENCV OPERATIONS
RESIZE_IMAGE = False
CHANGE_COLOR_SPACE = False
ADD_TEXT_TO_IMAGE = False
MODIFY_PIXEL_VALUE = False
FLIP_IMAGE = False
ROTATE_IMAGE_MULTIPLE_90 = True
CROP_IMAGE = False

# ADVANCED OPENCV OPERATIONS
EDGE_DETECTION = False
